
import java.util.ArrayList;
//import java.util.HashSet;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Claire Chemutai
 * @author Nanis Kanana
 */
public class BookRoom extends javax.swing.JFrame {
    CustomerService customer;
    ArrayList roomNum,roomHall;
    Intermediary inter;
    /**
     * Creates new form BookRoom
     * @param inter
     */
    public BookRoom(Intermediary inter) {
        this.customer=customer;
        initComponents();
        this.inter = inter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookRoomVar = new javax.swing.JLabel();
        bookRoomBtn = new javax.swing.JButton();
        cancelOrderBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomTableDisplay = new javax.swing.JTable();
        backRoomBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        bookRoomVar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        bookRoomVar.setText("ROOMS AVAILABLE");
        getContentPane().add(bookRoomVar);
        bookRoomVar.setBounds(80, 10, 230, 20);

        bookRoomBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bookRoomBtn.setText("BOOK");
        bookRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bookRoomBtn);
        bookRoomBtn.setBounds(10, 260, 90, 23);

        cancelOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelOrderBtn.setText("CANCEL");
        cancelOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOrderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelOrderBtn);
        cancelOrderBtn.setBounds(124, 258, 110, 23);

        roomTableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3S4", "A",  new Integer(2)},
                {"2H1", "C",  new Integer(1)},
                {"4K3", "D",  new Integer(3)},
                {"1K3", "B",  new Integer(2)}
            },
            new String [] {
                "Room No.", "Hall", "No. of Occupants"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(roomTableDisplay);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 36, 341, 188);

        backRoomBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backRoomBtn.setText("BACK");
        backRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backRoomBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backRoomBtn);
        backRoomBtn.setBounds(264, 258, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 380, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backRoomBtnActionPerformed
        // TODO add your handling code here:
        //CustomerService viewFood = new CustomerService (this);
        UserIdentification id = new UserIdentification(inter);
        this.setVisible(false);
        id.setVisible(true);
        
    }//GEN-LAST:event_backRoomBtnActionPerformed

    private void bookRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model3= (DefaultTableModel) roomTableDisplay.getModel();
        int roomBooked=roomTableDisplay.getSelectedRow();
        
        
        
        System.out.println("Booked room "+model3.getValueAt(roomBooked, 0).toString());
        inter.roomNum.add(model3.getValueAt(roomBooked, 0).toString());
        inter.roomHall.add(model3.getValueAt(roomBooked, 1).toString());
        
    }//GEN-LAST:event_bookRoomBtnActionPerformed

    private void cancelOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOrderBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model5= (DefaultTableModel) roomTableDisplay.getModel();
        int roomBooked=roomTableDisplay.getSelectedRow();
        String roomNumber=model5.getValueAt(roomBooked, 0).toString();
        
        
        for(int i=0;i<inter.roomNum.size();i++){
            if (inter.roomNum.get(i).equals(roomNumber))
                inter.roomNum.remove(roomNumber);
        }
        System.out.println("Room number "+ roomNumber+" successfully removed");
        
        
        
    }//GEN-LAST:event_cancelOrderBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backRoomBtn;
    private javax.swing.JButton bookRoomBtn;
    private javax.swing.JLabel bookRoomVar;
    private javax.swing.JButton cancelOrderBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable roomTableDisplay;
    // End of variables declaration//GEN-END:variables
}
