/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Claire Chemutai
 * @author Nanis Kanana
 */
public class TransactionsMade extends javax.swing.JFrame {
    StaffService staffTrans;
    /**
     * Creates new form TransactionsMade
     * @param staffTrans
     */
    public TransactionsMade(StaffService staffTrans) {
        this.staffTrans=staffTrans;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTextArea = new javax.swing.JTextArea();
        transBackBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("TRANSACTIONS MADE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 290, 30);

        transactionTextArea.setColumns(20);
        transactionTextArea.setRows(5);
        jScrollPane1.setViewportView(transactionTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(46, 65, 308, 195);

        transBackBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        transBackBtn.setText("BACK");
        transBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transBackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(transBackBtn);
        transBackBtn.setBounds(146, 278, 98, 32);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 11, 405, 7);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 420, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transBackBtnActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        staffTrans.setVisible(true);
    }//GEN-LAST:event_transBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton transBackBtn;
    public javax.swing.JTextArea transactionTextArea;
    // End of variables declaration//GEN-END:variables
}
